// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxolxbgsvbzvzochadnu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4b2x4YmdzdmJ6dnpvY2hhZG51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MTEyMjcsImV4cCI6MjA3MTI4NzIyN30.4ss_BQNshN7NVTOVarcu2DT2vPJUKJhZpI0pJAm32-w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});